# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Caohm's HomePage

description: > # this means to ignore newlines until "baseurl:"
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: "http://caohm.github.io"
permalink: /:year/:month/:day/:title/
# other links
github_username: caohm
email: caohongming001@gmail.com
weibo_username:
linkedin_username:

description_footer: Caohm's HomePage

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: caohm
duoshuo_url: "http://caohm.duoshuo.com"
#disqus_shortname:

# statistic analysis
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
#baidu_tongji_id: 01ead8d132fad393952a3d004d92453e
google_analytics_id: UA-91341681-1
# Build settings
markdown: kramdown
#theme: minima
kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
port: 80

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

gems:
  #- jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mermaid
  - jekyll-paginate

mermaid:
  src: '/js/mermaid.js'

# paginate
paginate: 5
paginate_path: "page:num"
# bundle
exclude:
  - Gemfile
  - Gemfile.lock



sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"